#### health check
GET http://localhost:3000/api/health_check

#### JSON example
GET http://localhost:3000/api/json_example

#### webhook
POST http://localhost:3000/api/line/webhook
Content-Type: application/json

{
  "destination": "{{$guid}}",
  "events": []
}
