#### Health check
GET http://localhost:3000/api/health_check

#### JSON response
GET http://localhost:3000/api/json_response

#### LINE webhook
POST http://localhost:3000/api/line/webhook
Content-Type: application/json

{
  "destination": "{{$guid}}",
  "events": []
}
